name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Selenoid Server
        uses: Xotabu4/selenoid-github-action@v2
        with:
          args: --browsers 'firefox:>90.0
      - uses: actions/checkout@v2
      - name: Run tests
        uses: gradle/gradle-build-action@v1.5.1
        with:
          arguments: test
          
      
      
